# Project: Suma C++
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Suma\ Fernando\ Berganza.o"
LINKOBJ  = "Suma Fernando Berganza.o"
LIBS     = -L"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/keyde/Documents/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Suma C++ Fernando Berganza.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\keyde\Documents\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Suma\ Fernando\ Berganza.o": Suma\ Fernando\ Berganza.cpp
	$(CPP) -c "Suma Fernando Berganza.cpp" -o "Suma Fernando Berganza.o" $(CXXFLAGS)
